accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
]

posts/urls.py
# POSTS URLS.PY
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',      views.IndexPage.as_view(), name='index'),
    url(r'test/',   views.TestLoginPage.as_view(), name='test'),
    url(r'thanks/', views.TestLogoutPage.as_view(), name='thanks'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Звездный Атлас</title>
    <!-- Latest Bootstrap 3.7 compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'social/css/master.css'%}">

</head>
<body>
    <nav class="navbar  mynav" role="navigation" id="navbar">
    	<div class="container">
            <a class="navbar-brand mynav" href="{% url 'index' %}">Звездный атлас</a>
    		<ul class="nav navbar-nav navbar-right">
    			{% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}" class="btn btn-simple">New Post</a></li>
                    <li><a href="{% url 'groups:all' %}  " class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'groups:create' %} " class="btn btn-simple">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    			{% else %}
                    <li><a href=" {% url 'groups:all' %}  " class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                    <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    			{% endif %}
    		</ul>
    	</div>
    </nav>
    <div class="container mycontent">
          {% block content %}
          {% endblock %}
    </div>
    <canvas id="canvas"></canvas>
</body>
<script src="{% static 'social/js/master.js'%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends 'base.html'  %}

{% block content %}
<h1>Звездный атлас</h1>

{% endblock %}

templates/test.html
{% extends 'base.html'  %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>LOGIN TEST PAGE</h1>
</div>


{% endblock %}

templates/thanks.html
{% extends 'base.html'  %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>LOGOUT TEST PAGE</h1>
</div>


{% endblock %}